name: build

on: [push, pull_request]

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]

      env:
        OS: ${{ matrix.os }}
        PYTHON: '3.9'

      steps:

        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            conda init bash
            conda create --name x python=3.9
            conda activate x
            conda install -c conda-forge esmpy
            python -m pip install --upgrade pip
            python -m pip install .
        - name: Test and generate coverage report on Linux
          run: |
            pip install pytest
            pip install pytest-cov
            pytest --cov=./ --cov-report=xml